[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
optimizer = true
optimizer_runs = 200
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./" }]
gas_reports = ["*"]
via_ir = true

metadata = true
metadata_hash = "none"     # disable ipfs
use_literal_content = true # use source code

# https://docs.monad.xyz/developer-essentials/network-information
# Monad Testnet Configuration
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143

[profile.ci.fuzz]
runs = 10_000
